name: test install script
on: [pull_request]
jobs:
  test:
    runs-on: [ubuntu-20.04]
    steps:
      - name: remote-bash
        uses: shinhwagk/remote-bash@0.0.1
        with:
          args:
        env:
          REMOTE_BASH_URL: https://github.com/NarutoXY/pacstall/raw/fix-ci/.github/workflows/workflow.sh
